"""empty message

Revision ID: 074f27c81842
Revises: 
Create Date: 2022-02-28 01:25:48.511700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '074f27c81842'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading', sa.Column('temp', sa.Float(), nullable=False))
    op.add_column('reading', sa.Column('hum', sa.Float(), nullable=False))
    op.add_column('reading', sa.Column('time_taken', sa.DateTime(), nullable=True))
    op.drop_column('reading', 'humidity')
    op.drop_column('reading', 'time')
    op.drop_column('reading', 'temperature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading', sa.Column('temperature', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('reading', sa.Column('humidity', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('reading', 'time_taken')
    op.drop_column('reading', 'hum')
    op.drop_column('reading', 'temp')
    # ### end Alembic commands ###
