"""empty message

Revision ID: d64d527d9eb9
Revises: d0be3ff6e05d
Create Date: 2022-04-09 10:57:53.170518

"""
from alembic import op
import sqlalchemy as sa

import os

hum_high = os.environ.get("HUMIDITY_HIGH_SP")
hum_low = os.environ.get("HUMIDITY_LOW_SP")


# revision identifiers, used by Alembic.
revision = 'd64d527d9eb9'
down_revision = 'd0be3ff6e05d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environmentconfig', sa.Column('humidity_high_sp', sa.Float(), nullable=True))
    op.add_column('environmentconfig', sa.Column('humidity_low_sp', sa.Float(), nullable=True))
    op.execute(f"UPDATE environmentconfig SET humidity_high_sp = {hum_high}")
    op.execute(f"UPDATE environmentconfig SET humidity_low_sp = {hum_low}")
    op.alter_column("environmentconfig", "humidity_high_sp", nullable=False)
    op.alter_column("environmentconfig", "humidity_low_sp", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environmentconfig', 'humidity_low_sp')
    op.drop_column('environmentconfig', 'humidity_high_sp')
    # ### end Alembic commands ###
